// Code generated by protoc-gen-go. DO NOT EDIT.
// source: searh.proto

package go_micro_srv_search

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	QueryText            string   `protobuf:"bytes,1,opt,name=queryText,proto3" json:"queryText,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8d9dd11291e51b, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetQueryText() string {
	if m != nil {
		return m.QueryText
	}
	return ""
}

func (m *Request) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type Response struct {
	EntityIds            []int64  `protobuf:"varint,1,rep,packed,name=entityIds,proto3" json:"entityIds,omitempty"`
	CountAll             int64    `protobuf:"varint,2,opt,name=countAll,proto3" json:"countAll,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e8d9dd11291e51b, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetEntityIds() []int64 {
	if m != nil {
		return m.EntityIds
	}
	return nil
}

func (m *Response) GetCountAll() int64 {
	if m != nil {
		return m.CountAll
	}
	return 0
}

func (m *Response) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "go.tutu.srv.search.Request")
	proto.RegisterType((*Response)(nil), "go.tutu.srv.search.Response")
}

func init() { proto.RegisterFile("searh.proto", fileDescriptor_5e8d9dd11291e51b) }

var fileDescriptor_5e8d9dd11291e51b = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x18, 0x95, 0xf6, 0xd8, 0x6e, 0xb2, 0x4a, 0x87, 0x28, 0x53, 0x26, 0x0f, 0xf0, 0x0b,
	0x18, 0x2b, 0x31, 0x39, 0x48, 0xb0, 0x96, 0x70, 0x4a, 0x22, 0x45, 0x71, 0x62, 0x9f, 0x11, 0xe1,
	0xd7, 0x23, 0x3b, 0x51, 0x32, 0xd0, 0xc9, 0xf7, 0xde, 0x93, 0xde, 0x87, 0xe1, 0xc1, 0xd3, 0xc5,
	0x35, 0x7a, 0x70, 0x96, 0x2d, 0x62, 0x6d, 0x35, 0x07, 0x0e, 0xda, 0xbb, 0x6f, 0x1d, 0x85, 0xaa,
	0xc9, 0xdf, 0xe1, 0xde, 0xd0, 0x18, 0xc8, 0x33, 0x9e, 0xe0, 0x30, 0x06, 0x72, 0xd3, 0x1b, 0xfd,
	0xb0, 0x12, 0x99, 0x28, 0x0e, 0x66, 0x23, 0x10, 0xe1, 0x6e, 0xb8, 0xd4, 0xa4, 0x6e, 0x33, 0x51,
	0x48, 0x93, 0x6e, 0x3c, 0xc2, 0x3e, 0xbe, 0x65, 0xfb, 0x4b, 0x4a, 0x26, 0x7e, 0xc5, 0xf9, 0x07,
	0xec, 0x0d, 0xf9, 0xc1, 0xf6, 0x9e, 0xa2, 0x33, 0xf5, 0xdc, 0xf2, 0x74, 0xfe, 0xf2, 0x4a, 0x64,
	0xb2, 0x90, 0x66, 0x23, 0xa2, 0x4b, 0x65, 0x43, 0xcf, 0x2f, 0x5d, 0xb7, 0xb8, 0xaf, 0x78, 0x4d,
	0x95, 0x5b, 0xea, 0x53, 0x09, 0xbb, 0x32, 0x95, 0xc7, 0x33, 0xc0, 0x7c, 0xbd, 0xb6, 0x9e, 0xf1,
	0x51, 0xff, 0xdf, 0xa7, 0x97, 0x71, 0xc7, 0xd3, 0x75, 0x71, 0x2e, 0x98, 0xdf, 0x7c, 0xee, 0xd2,
	0x17, 0x3d, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x5f, 0x3d, 0x92, 0x31, 0x01, 0x00, 0x00,
}
