// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: fileinfo.proto

/*
Package go_tutu_srv_fileinfo is a generated protocol buffer package.

It is generated from these files:
	fileinfo.proto

It has these top-level messages:
	EntityId
	Request
	AppInfo
	Response
*/
package go_micro_srv_fileinfo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FileInfo service

type FileInfoService interface {
	GetAppInfoByEntityId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type fileInfoService struct {
	c    client.Client
	name string
}

func NewFileInfoService(name string, c client.Client) FileInfoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.tutu.srv.fileinfo"
	}
	return &fileInfoService{
		c:    c,
		name: name,
	}
}

func (c *fileInfoService) GetAppInfoByEntityId(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "FileInfo.GetAppInfoByEntityId", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FileInfo service

type FileInfoHandler interface {
	GetAppInfoByEntityId(context.Context, *Request, *Response) error
}

func RegisterFileInfoHandler(s server.Server, hdlr FileInfoHandler, opts ...server.HandlerOption) error {
	type fileInfo interface {
		GetAppInfoByEntityId(ctx context.Context, in *Request, out *Response) error
	}
	type FileInfo struct {
		fileInfo
	}
	h := &fileInfoHandler{hdlr}
	return s.Handle(s.NewHandler(&FileInfo{h}, opts...))
}

type fileInfoHandler struct {
	FileInfoHandler
}

func (h *fileInfoHandler) GetAppInfoByEntityId(ctx context.Context, in *Request, out *Response) error {
	return h.FileInfoHandler.GetAppInfoByEntityId(ctx, in, out)
}
